### ISSUE TITLE
kover: Unknown option 'genomic-data'

### ISSUE THREAD

**Issue by samyuktr** [aldro61/kover#50]
I have kover successfully installed. 
```
$:~/kover$ kover --version
libcdio 0.83
    Copyright (C) 1998, 2000 by Denis Oliver Kropp
    Copyright (C) 2000, 2008 by Adrian Reber
libcdio comes with ABSOLUTELY NO WARRANTY - for details read the license.
Qt: 4.8.7
KDE Development Platform: 4.14.16
libcdio: 0.83
$:~/kover$ python -c "import kover"
$:~/kover$
```
I am trying to run the example data found at - [http://aldro61.github.io/kover/doc_tut_scm.html](http://aldro61.github.io/kover/doc_tut_scm.html)
When I try and run the command mentioned in the above link - 

 `kover dataset create from-tsv --genomic-data KmerMatrix.tsv --phenotype-description "Rifampicin resistance" --phenotype-metadata metadata.tsv --output example.kover --progress`

This is what I get - 

```
$:~/kover$ kover dataset create from-tsv --genomic-data KmerMatrix.tsv --phenotype-description "Rifampicin resistance" --phenotype-metadata metadata.tsv --output example.kover --progress
libcdio 0.83
    Copyright (C) 1998, 2000 by Denis Oliver Kropp
    Copyright (C) 2000, 2008 by Adrian Reber
libcdio comes with ABSOLUTELY NO WARRANTY - for details read the license.
kover: Unknown option 'genomic-data'.
kover: Use --help to get a list of available command line options.
```

Please let me know what I'm missing.

**Comment by aldro61** [comment]
Hi @samyuktr,

What do you get when you run `kover dataset create from-tsv --help`? You should be getting the following:

```
➜  ~ kover dataset create from-tsv
usage: kover dataset create from-tsv [-h] --genomic-data GENOMIC_DATA
                                     [--phenotype-description PHENOTYPE_DESCRIPTION]
                                     [--phenotype-metadata PHENOTYPE_METADATA]
                                     --output OUTPUT
                                     [--compression COMPRESSION] [-x] [-v]

Creates a Kover dataset from genomic data and optionally phenotypic metadata

optional arguments:
  -h, --help            show this help message and exit
  --genomic-data GENOMIC_DATA
                        A tab-separated file containing the k-mer matrix.
  --phenotype-description PHENOTYPE_DESCRIPTION
                        An informative description that is assigned to the
                        phenotypic metadata.
  --phenotype-metadata PHENOTYPE_METADATA
                        A file containing the phenotypic metadata.
  --output OUTPUT       The Kover dataset to be created.
  --compression COMPRESSION
                        The gzip compression level (0 - 9). 0 means no
                        compression. The default value is 4.
  -x, --progress        Shows a progress bar for the execution.
  -v, --verbose         Sets the verbosity level.
```

I'm not sure why you are getting output from `libcdio` and `QT` when running commands and have never encountered this in the past. If you want to be certain that your installation is correct, you can try running from our preconfigured docker image: https://hub.docker.com/r/aldro61/kover.

**Comment by aldro61** [comment]
Can you also attach the output of `kover --help`? 

Thanks!
Alex

**Comment by samyuktr** [comment]
Hi @aldro61, 

Thank you for the quick response. 
Here's what I see - 

```
~$ kover dataset create from-tsv --help
libcdio 0.83
    Copyright (C) 1998, 2000 by Denis Oliver Kropp
    Copyright (C) 2000, 2008 by Adrian Reber
libcdio comes with ABSOLUTELY NO WARRANTY - for details read the license.
Usage: kover [Qt-options] [KDE-options] [URL]

Kover is an easy to use WYSIWYG CD cover printer with CDDB support.

Generic options:
  --help                    Show help about options
  --help-qt                 Show Qt specific options
  --help-kde                Show KDE specific options
  --help-all                Show all options
  --author                  Show author information
  -v, --version             Show version information
  --license                 Show license information
  --                        End of options

Arguments:
  URL                       Document to open

Options:
  --advise                  Help me now!
  --debug                   Enable debug output
~$ kover --help
libcdio 0.83
    Copyright (C) 1998, 2000 by Denis Oliver Kropp
    Copyright (C) 2000, 2008 by Adrian Reber
libcdio comes with ABSOLUTELY NO WARRANTY - for details read the license.
Usage: kover [Qt-options] [KDE-options] [URL]

Kover is an easy to use WYSIWYG CD cover printer with CDDB support.

Generic options:
  --help                    Show help about options
  --help-qt                 Show Qt specific options
  --help-kde                Show KDE specific options
  --help-all                Show all options
  --author                  Show author information
  -v, --version             Show version information
  --license                 Show license information
  --                        End of options

Arguments:
  URL                       Document to open

Options:
  --advise                  Help me now!
  --debug                   Enable debug output
```
Could you please give me more instructions on how to run the docker image? 

Thanks, 
Samyukta

**Comment by aldro61** [comment]
Hey @samyuktr, it seems like the kover program that your computer is seeing is not my Kover :D It's probably another program with the exact same name. If you run `which kover`, you should see that it's not pointing to what you installed using this repo. I would try to solve this issue first before diving into Docker. Maybe uninstall that program using your system's package manager if you're not using it.

Did you follow the last step of the install process, where you had to create a symbolic link to kover in your /usr/bin directory?

**Comment by samyuktr** [comment]
Haha. You're right. I had some other version installed. I now uninstalled the other one and I'm using your version. 
But I'm still unable to run `kover dataset create`. Here's what I see. 
```
~/kover-example$  kover dataset create from-tsv --help
usage: kover dataset create from-tsv [-h] --genomic-data GENOMIC_DATA
                                     [--phenotype-description PHENOTYPE_DESCRIPTION]
                                     [--phenotype-metadata PHENOTYPE_METADATA]
                                     --output OUTPUT
                                     [--compression COMPRESSION] [-x] [-v]

Creates a Kover dataset from genomic data and optionally phenotypic metadata

optional arguments:
  -h, --help            show this help message and exit
  --genomic-data GENOMIC_DATA
                        A tab-separated file containing the k-mer matrix.
  --phenotype-description PHENOTYPE_DESCRIPTION
                        An informative description that is assigned to the
                        phenotypic metadata.
  --phenotype-metadata PHENOTYPE_METADATA
                        A file containing the phenotypic metadata.
  --output OUTPUT       The Kover dataset to be created.
  --compression COMPRESSION
                        The gzip compression level (0 - 9). 0 means no
                        compression. The default value is 4.
  -x, --progress        Shows a progress bar for the execution.
  -v, --verbose         Sets the verbosity level.
```
```
~/kover-example$ which kover
/.../kover/bin/kover

~/kover-example$ kover dataset create from-tsv --genomic-data KmerMatrix.tsv --phenotype-description "Rifampicin resistance" --phenotype-metadata metadata.tsv --output example.kover --progress
Traceback (most recent call last):
  File "/.../kover/bin/kover", line 1192, in <module>
    CommandLineInterface()
  File "/.../kover/bin/kover", line 1150, in __init__
    getattr(self, args.command)()
  File "/.../kover/bin/kover", line 1170, in dataset
    getattr(dataset_tool, args.command)()
  File "/.../kover/bin/kover", line 250, in create
    getattr(creation_tool, args.datasource)()
  File "/.../kover/bin/kover", line 91, in from_tsv
    from kover.dataset.create import from_tsv
ImportError: No module named kover.dataset.create
```

**Comment by samyuktr** [comment]
[Koverinstall.log](https://github.com/aldro61/kover/files/3678078/Koverinstall.log)
^^ Attaching the output from my `./install.sh`

**Comment by aldro61** [comment]
Thanks, the install log is perfectly clean.

Is it possible that your system defaults to Python 3? The installer correctly uses Python 2.7 (as per the log), but if your system defaults to Python 3, it would be normal that it doesn't find the package installed with Python 2.7. What happens if you run `which python` in a new terminal?

Also, does `python -c 'import kover; print(kover)'` work? If it does print the directory where Kover is installed, can you please post it here and also post the result of `echo $PYTHONPATH`.

**Comment by samyuktr** [comment]
You're right. It was pulling a different python version when I ran the kover command. 
I was able to fix it :) 

Thank you for your help! 

One last question, is there a script to generate data files like the one in the example set?

**Comment by aldro61** [comment]
You're welcome, I'm glad it works now!

For the data files, I don't have a script to do it. We used Ray Surveyor, for which you can find a tutorial here: https://github.com/zorino/raysurveyor-tutorial. In our latest paper, we favored the `kover dataset create from-contigs` option, which creates the k-mer matrix directly in kover from contig files (fasta).

**Comment by samyuktr** [comment]
Thank you!!
