### ISSUE TITLE
`kover learn scm` throws TypeError for some values of the split random seed

### ISSUE THREAD

**Issue by goepp** [aldro61/kover#54]
I use a simple example from simulated data, with 1000 individuals and 100 features. 
The scm implementation throws a `TypeError: Indexing elements must be in increasing order` exception. 
This error occurs only for some values of the random seed that I use in the `kover dataset split`command, indicating that the bug is linked to the division of the data into train and test sets.
The kover dataset is generated from tsv files; a reproducible example is provided in the attached file: [reprex.tar.gz](https://github.com/aldro61/kover/files/4878311/reprex.tar.gz).

**Comment by aldro61** [comment]
Hi @goepp! 

Thanks for reaching out. Could you please provide the following additional information to help me reproduce:

1. Dataset creation command that you used
2. Dataset split command that you used
3. The Python stack trace for the error (I especially want to figure out in which file/line it fails).

Thanks in advance!
Alex

**Comment by goepp** [comment]
Sorry, I attached the wrong file.
[This archive](https://github.com/aldro61/kover/files/4879231/reprex.tar.gz) includes the text file "reproducible_example" the list of commands that reproduce the error.
I copy this file here for clarity:
### Create dataset
`kover dataset create from-tsv --genomic-data design.tsv --phenotype-metadata phenotype.tsv --phenotype-description reprex --output reprex.kover`

### Split1: no error
`kover dataset split --dataset reprex.kover --id split1 --random-seed 1 --progress`
`kover learn scm --dataset reprex.kover --split split1 --hp-choice bound --progress`

### Split2: throws 'TypeError: Indexing elements must be in increasing order'
`kover dataset split --dataset reprex.kover --id split2 --random-seed 2 --progress`
`kover learn scm --dataset reprex.kover --split split2 --hp-choice bound --progress`

The last command throws the following error stack:

> Traceback (most recent call last):                  |Elapsed Time: 0:00:00
  File "/usr/local/bin/kover/bin/kover", line 1192, in <module>
    CommandLineInterface()
  File "/usr/local/bin/kover/bin/kover", line 1150, in __init__
    getattr(self, args.command)()
  File "/usr/local/bin/kover/bin/kover", line 1189, in learn
    getattr(learning_tool, args.command)()
  File "/usr/local/bin/kover/bin/kover", line 574, in scm
    progress_callback=progress)
  File "/usr/local/lib/python2.7/dist-packages/kover/learning/experiments/experiment_scm.py", line 499, in learn_SCM
    error_callback =error_callback)
  File "/usr/local/lib/python2.7/dist-packages/kover/learning/experiments/experiment_scm.py", line 395, in _bound_selection
    product(model_types, p_values)):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
TypeError: Indexing elements must be in increasing order


Thank you very much!

**Comment by aldro61** [comment]
Thank you! Will try to reproduce and get back to you.

**Comment by aldro61** [comment]
I confirm that I was able to reproduce this using the files/commands you provided and the Docker image version of Kover. Will investigate more.

**Comment by aldro61** [comment]
The exception occurs [here](https://github.com/aldro61/kover/blob/06574edd3a8db92b29180de7b65f191c844ca142/core/kover/learning/experiments/experiment_scm.py#L77) because `columns_to_load` contains the same index twice. Looking at the verbose output of the model, I see that it's adding a rule based on `SNP001` to the model twice. The question now is why this occurs.

**Comment by aldro61** [comment]
Alright! I figure this out. There was indeed a bug in the code. Fortunately, it is an edge case that is not likely to arise in very high dimensional datasets. Details below:

## Nature of the bug
* In [rules.py](https://github.com/aldro61/kover/blob/kover2/core/kover/learning/common/rules.py), we optimize computations by calculating rule classifications for "presence" rules only. We can infer the "absence" rules by inverting the predictions of "presence rules.
* The `KmerRuleClassifications` implicitly defines a matrix where the first `n_features` columns are for presence rules and the subsequent columns are for absence rules.
* Your dataset had 100 features, so 100 presence rules and 100 absence rules
* The best rule had index 100, which corresponds to absence(SNP001), which is equivalent to not(presence(SNP001))
* So in this case, the code should've 1) looked at the value of feature 0 in all examples, 2) inverted the values.
* However, the current code has a bug that does not invert the first absence rule (only).
* The faulty line is [here](https://github.com/aldro61/kover/blob/06574edd3a8db92b29180de7b65f191c844ca142/core/kover/learning/common/rules.py#L153). Here, `>` should be `>=`.
## Solution
