### ISSUE TITLE
Issue running dataset create

### ISSUE THREAD

**Issue by gracehm** [aldro61/kover#62]
Hello,
I am struggling to get this program running on my new computer. I had it working previously and now that I have moved, I am getting this error: 
Traceback (most recent call last):
  File "/home/NAME/kover/bin/kover", line 1192, in <module>
    CommandLineInterface()
  File "/home/NAME/kover/bin/kover", line 1150, in __init__
    getattr(self, args.command)()
  File "/home/NAME/kover/bin/kover", line 1170, in dataset
    getattr(dataset_tool, args.command)()
  File "/home/NAME/kover/bin/kover", line 250, in create
    getattr(creation_tool, args.datasource)()
  File "/home/NAME/kover/bin/kover", line 159, in from_contigs
    progress=args.progress)
  File "/home/NAME/miniconda3/envs/kover/lib/python2.7/site-packages/kover/dataset/create.py", line 371, in from_contigs
    progress=progress)
  File "/home/NAME/miniconda3/envs/kover/lib/python2.7/site-packages/kover/dataset/tools/kmer_count.py", line 37, in contigs_count_kmers
    "-progress", str(progress)])
  File "/home/NAME/miniconda3/envs/kover/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/NAME/miniconda3/envs/kover/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/NAME/miniconda3/envs/kover/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Any suggestions to fix this?

**Comment by aldro61** [comment]
Hi,

It looks like the compiled portion of the program cannot be found. I suspect it failed to compile during the installation process. Could you re-run the installer and look for any errors during compilation?
